// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9g-fdj3tK6VMFEZbPnpIPLhKY6OzHLeY',
    appId: '1:489698765155:android:ac2405fd3fa3db73e14b56',
    messagingSenderId: '489698765155',
    projectId: 'deal-station-66c0b',
    storageBucket: 'deal-station-66c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAms8FVN75M1y-Aj1GqIgqa3raOghXYrI',
    appId: '1:489698765155:ios:606c9592e5c01285e14b56',
    messagingSenderId: '489698765155',
    projectId: 'deal-station-66c0b',
    storageBucket: 'deal-station-66c0b.appspot.com',
    iosClientId: '489698765155-e1uinkrgsg8l4b53h9ds2ni2ka50utqi.apps.googleusercontent.com',
    iosBundleId: 'com.app.memberApp',
  );
}
